AFS_Dev/src/objects/Attribute__c.object
<CustomObject>
    <fields>
        <fullName>AttributePercent__c</fullName>
        <label>Attribute %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Attribute_TCR__c</fullName>
        <formula>IF( OR(  ISPICKVAL(Attribute_Type__c, &apos;IO Offerings&apos;)  ,ISPICKVAL(Attribute_Type__c, &apos;MC Offerings&apos;),ISPICKVAL(Attribute_Type__c, &apos;SI Offerings&apos;),ISPICKVAL(Attribute_Type__c, &apos;TC Offerings&apos;),ISPICKVAL(Attribute_Type__c, &apos;AO Offerings&apos;)) , 

 NULL,

 Opportunity_Name__r.Total_Current_Revenue__c *  AttributePercent__c)</formula>
        <label>Attribute TCR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <label>Attribute Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accenture Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMIN:Digital Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMIN:Digital Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horizontals/Initiatives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TC Offerings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ventures &amp; Acquisitions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attribute_Value__c</fullName>
        <label>Attribute Value</label>
        <picklist>
            <controllingField>Attribute_Type__c</controllingField>
            <picklistValues>
                <fullName>Accenture Cloud Platform-Cloud Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADOBE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFS - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agilex - Standalone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agilex - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMAZON WEB SERVICES (AWS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Application Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Application Modernization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Capacity Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Microsoft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Testing Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO-Workday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIGEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Modernization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASM - Synergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALLIDUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CISCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLICKSOFTWARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Agile Infrastructure (IaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Apps and Platform Services (PaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Business Process as a Service (BPaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-SaaS Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud-Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyber</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>Att-{0000000000}</displayFormat>
        <label>Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AFS_Dev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Reporting_Status__c</fullName>
        <inlineHelpText>Field updated based on the stage of the opportunity through workflow. Reporting Status is a read-only field used for reporting purposes.</inlineHelpText>
        <label>Reporting Status</label>
        <picklist>
            <controllingField>Approved_Status_Stage__c</controllingField>
            <picklistValues>
                <fullName>Lost</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Client Withdrew</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>AFS Withdrew</fullName>
                <color>#33CCFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Current_Revenue__c</fullName>
        <inlineHelpText>The total sales number/booking for the entire opportunity. Total Current Revenue is a read-only field that is populated from the Financial Details Related List.</inlineHelpText>
        <label>Total Current Revenue</label>
        <summarizedField>OpportunityLineItem.Revenue__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

AFS_Dev/src/classes/UnqualifiedReportController.cls
public class UnqualifiedReportController {

    public List<Attribute__c> digitalPipeline {get; set;}
    public List<Attribute__c> nonDigitalPipeline {get; set;}
    public List<Attribute__c> noAttributePipeline {get; set;}
    public List<Attribute__c> grandTotal {get; set;}
    public Map<Id, Opportunity> allOpportunities {get; set;}
    public Integer digitalSize {get; set;}
    public Integer nonDigitalSize {get; set;}
    public Integer noAttributeSize {get; set;}
    public Integer grandTotalSize {get; set;}
    public String digitalSum {get; set;}
    public String nonDigitalSum {get; set;}
    public String noAttributeSum {get; set;}
    public String digitalOppSum {get; set;}
    public String nonDigitalOppSum {get; set;}
    public String noAttributeOppSum {get; set;}
    public String grandSum {get; set;}
    public String grandOppSum {get; set;}
    
  
    public PageReference getReport() {
        allOpportunities = new Map<Id, Opportunity>([
        SELECT Id, Total_Current_Revenue__c FROM Opportunity WHERE  Reporting_Status__c = 'Unqualified'  
        ]);
        
        
        digitalPipeline = new List<Attribute__c>();
        nonDigitalPipeline = new List<Attribute__c>();
        noAttributePipeline = new List<Attribute__c>();
        grandTotal = new List<Attribute__c>();
        Set<Id> oppWithAttribute = new Set<Id>();
        Decimal dSum = 0;
        Decimal ndSum = 0;
        Decimal noAttSum = 0;
        Decimal dOppSum = 0;
        Decimal ndOppSum = 0;
        Decimal noAttOppSum = 0;
        Decimal grandTotalOppTCR = 0;
        
        Set<Id> digitalOpp = new Set<Id>();
        Set<Id> nonDigitalOpp = new Set<Id>();
        Set<Id> allOpp = new Set<Id>();
        for(Attribute__c attribute : [SELECT Opportunity_Name__c, Attribute_Type__c, Attribute_Value__c, Attribute_TCR__c, AttributePercent__c
                                        FROM Attribute__c WHERE Opportunity_Name__c IN :allOpportunities.keySet()]){
            oppWithAttribute.add(attribute.Opportunity_Name__c);
            Decimal tcr = 0;
            if(attribute.Attribute_TCR__c != null){
                tcr = attribute.Attribute_TCR__c;
            }
            
            Decimal oppTcr = 0;
            if(allOpportunities.get(attribute.Opportunity_Name__c).Total_Current_Revenue__c != null){
                oppTcr = allOpportunities.get(attribute.Opportunity_Name__c).Total_Current_Revenue__c;
            }
            
            if(attribute.Attribute_Type__c.equals('Accenture Digital')){
                digitalPipeline.add(attribute);
                dSum += tcr;
                if(!digitalOpp.contains(attribute.Opportunity_Name__c)){
                    dOppSum += oppTcr;
                    digitalOpp.add(attribute.Opportunity_Name__c);
                }
            }
            else{
                nonDigitalPipeline.add(attribute);
                ndSum += tcr;
                if(!nonDigitalOpp.contains(attribute.Opportunity_Name__c)){
                    ndOppSum += oppTcr;
                    nonDigitalOpp.add(attribute.Opportunity_Name__c);
                }
            }
            
            if(!allOpp.contains(attribute.Opportunity_Name__c)){
                grandTotalOppTCR += oppTcr;
                allOpp.add(attribute.Opportunity_Name__c);
            }
        }
        
        for(Id oppId : allOpportunities.keySet()){
            if(!oppWithAttribute.contains(oppId)){
                noAttributePipeline.add(new Attribute__c(
                    Opportunity_Name__c = oppId,
                    Attribute_Type__c = '-',
                    Attribute_Value__c = '-',
                    AttributePercent__c = null
                    ));
                noAttOppSum += allOpportunities.get(oppId).Total_Current_Revenue__c;
                grandTotalOppTCR += allOpportunities.get(oppId).Total_Current_Revenue__c;
            }
        }
        
        digitalSize = digitalPipeline.size();
        nonDigitalSize = nonDigitalPipeline.size();
        noAttributeSize = noAttributePipeline.size();
        grandTotalSize = digitalSize + nonDigitalSize + noAttributeSize;
        
        digitalSum = dSum.format();
        nonDigitalSum = ndSum.format();
        noAttributeSum = noAttSum.format();
        digitalOppSum = dOppSum.format();
        nonDigitalOppSum = ndOppSum.format();
        noAttributeOppSum = noAttOppSum.format();
        grandSum = (dSum + ndSum + noAttSum).format();
        grandOppSum = grandTotalOppTCR.format();
        
        
        return null;
    }
    
    public PageReference getReports() {
        allOpportunities = new Map<Id, Opportunity>([
        SELECT Id, Total_Current_Revenue__c FROM Opportunity WHERE  Reporting_Status__c = 'Unqualified'  
        ]);
        
        
        digitalPipeline = new List<Attribute__c>();
        nonDigitalPipeline = new List<Attribute__c>();
        noAttributePipeline = new List<Attribute__c>();
        grandTotal = new List<Attribute__c>();
        Set<Id> oppWithAttribute = new Set<Id>();
        Decimal dSum = 0;
        Decimal ndSum = 0;
        Decimal noAttSum = 0;
        Decimal dOppSum = 0;
        Decimal ndOppSum = 0;
        Decimal noAttOppSum = 0;
        Decimal grandTotalOppTCR = 0;
        
        Set<Id> digitalOpp = new Set<Id>();
        Set<Id> nonDigitalOpp = new Set<Id>();
        Set<Id> allOpp = new Set<Id>();
        for(Attribute__c attribute : [SELECT Opportunity_Name__c, Attribute_Type__c, Attribute_Value__c, Attribute_TCR__c, AttributePercent__c
                                        FROM Attribute__c WHERE Opportunity_Name__c IN :allOpportunities.keySet()]){
            oppWithAttribute.add(attribute.Opportunity_Name__c);
            Decimal tcr = 0;
            if(attribute.Attribute_TCR__c != null){
                tcr = attribute.Attribute_TCR__c;
            }
            
            Decimal oppTcr = 0;
            if(allOpportunities.get(attribute.Opportunity_Name__c).Total_Current_Revenue__c != null){
                oppTcr = allOpportunities.get(attribute.Opportunity_Name__c).Total_Current_Revenue__c;
            }
            
            if(attribute.Attribute_Type__c.equals('Accenture Digital')){
                digitalPipeline.add(attribute);
                dSum += tcr;
                if(!digitalOpp.contains(attribute.Opportunity_Name__c)){
                    dOppSum += oppTcr;
                    digitalOpp.add(attribute.Opportunity_Name__c);
                }
            }
            else{
                nonDigitalPipeline.add(attribute);
                ndSum += tcr;
                if(!nonDigitalOpp.contains(attribute.Opportunity_Name__c)){
                    ndOppSum += oppTcr;
                    nonDigitalOpp.add(attribute.Opportunity_Name__c);
                }
            }
            
            if(!allOpp.contains(attribute.Opportunity_Name__c)){
                grandTotalOppTCR += oppTcr;
                allOpp.add(attribute.Opportunity_Name__c);
            }
        }
        
        for(Id oppId : allOpportunities.keySet()){
            if(!oppWithAttribute.contains(oppId)){
                nonDigitalPipeline.add(new Attribute__c(
                    Opportunity_Name__c = oppId,
                    Attribute_Type__c = null,
                    Attribute_Value__c = null,
                    AttributePercent__c = null
                    ));
                ndOppSum += allOpportunities.get(oppId).Total_Current_Revenue__c;
                grandTotalOppTCR += allOpportunities.get(oppId).Total_Current_Revenue__c;
            }
        }
        
        digitalSize = digitalPipeline.size();
        nonDigitalSize = nonDigitalPipeline.size();
        grandTotalSize = digitalSize + nonDigitalSize;
        
        digitalSum = dSum.format();
        nonDigitalSum = ndSum.format();
        digitalOppSum = dOppSum.format();
        nonDigitalOppSum = ndOppSum.format();
        grandSum = (dSum + ndSum).format();
        grandOppSum = grandTotalOppTCR.format();
        
        
        return null;
    }
    

}